apiVersion: apps/v1
kind: Deployment

metadata:
  name: college-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: college-app

  template:
    metadata:
      labels:
        app: college-app

    spec:
      containers:
        - name: college-app

          image: prachigore19/college-app:1.0

          imagePullPolicy: Always

          ports:
            - containerPort: 8090

          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: college-app-config
                  key: MONGODB_URI
