# ==========================================
# Spring Boot Application
# ==========================================

spring.application.name=college-app

# Spring Boot server
server.port=8090


# ==========================================
# MongoDB Configuration
# ==========================================

# MongoDB connection string
# Replace the IP/hostname with your MongoDB server.
spring.data.mongodb.uri=${MONGODB_URI}

# Database
spring.data.mongodb.database=college


# ==========================================
# Logging
# ==========================================

logging.level.org.springframework.data.mongodb=INFO
logging.level.org.mongodb.driver=INFO
